import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'
import { getTranslations, getLocale } from 'next-intl/server'

export async function generateMetadata(): Promise<Metadata> {
  const t = await getTranslations('privacy')
  return { title: `${t('title')} — Seoul 30` }
}

export default async function PrivacyPage() {
  const t = await getTranslations('privacy')
  const locale = await getLocale()
  const isKo = locale === 'ko'

  const sections = isKo
    ? [
        {
          title: '수집하는 개인정보',
          body: 'Seoul 30은 이름, 이메일, 전화번호 등 개인 식별 정보를 수집하지 않습니다.',
        },
        {
          title: '기기 내 저장 (localStorage)',
          body: '북마크와 최근 본 장소 목록은 사용자의 기기 내 localStorage에만 저장됩니다. 서버로 전송되지 않으며, 언제든지 브라우저 설정에서 삭제할 수 있습니다.\n\n장소 평가(좋아요/싫어요) 기능은 중복 방지를 위해 임의 세션 ID(UUID)를 생성해 localStorage에 저장합니다. 이 값은 개인 식별에 사용되지 않습니다.',
        },
        {
          title: '푸시 알림',
          body: '알림 구독 시 브라우저가 생성한 Push 엔드포인트 URL이 데이터베이스에 저장됩니다. 이 값은 알림 발송에만 사용되며 개인 식별이 불가능합니다. 구독 해제 시 즉시 삭제됩니다.',
        },
        {
          title: '외부 서비스',
          body: '지도 타일은 OpenStreetMap(openstreetmap.org)에서 제공됩니다. 장소 정보와 혼잡도 데이터는 서울시 열린데이터광장 API를 통해 서버 측에서만 조회합니다. Vercel Analytics를 통해 방문 통계(익명)를 수집할 수 있습니다.',
        },
        {
          title: '문의',
          body: 'GitHub Issues를 통해 문의하실 수 있습니다.',
        },
      ]
    : [
        {
          title: 'Personal data collected',
          body: 'Seoul 30 does not collect any personally identifiable information such as name, email, or phone number.',
        },
        {
          title: 'On-device storage (localStorage)',
          body: 'Bookmarks and recently viewed places are stored only in your browser\'s localStorage. Nothing is sent to our servers. You can clear this data at any time in your browser settings.\n\nThe place rating feature (thumbs up/down) generates a random session ID (UUID) stored in localStorage to prevent duplicate votes. This value cannot identify you personally.',
        },
        {
          title: 'Push notifications',
          body: 'When you subscribe to push notifications, the push endpoint URL generated by your browser is stored in our database. It is used solely to deliver notifications and cannot identify you. It is deleted immediately upon unsubscription.',
        },
        {
          title: 'Third-party services',
          body: 'Map tiles are provided by OpenStreetMap (openstreetmap.org). Place and congestion data is fetched from the Seoul Open Data Plaza API on the server side only. Vercel Analytics may collect anonymous visit statistics.',
        },
        {
          title: 'Contact',
          body: 'You can reach us via GitHub Issues.',
        },
      ]

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-2xl mx-auto px-4 py-6">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground mb-6"
        >
          <ArrowLeft className="w-4 h-4" aria-hidden="true" />
          {isKo ? '홈으로' : 'Home'}
        </Link>

        <h1 className="text-2xl font-bold text-foreground mb-1">{t('title')}</h1>
        <p className="text-xs text-muted-foreground mb-8">
          {isKo ? '최종 수정: 2026년 5월' : 'Last updated: May 2026'}
        </p>

        <div className="space-y-6">
          {sections.map((s) => (
            <section key={s.title}>
              <h2 className="text-base font-semibold text-foreground mb-2">{s.title}</h2>
              {s.body.split('\n\n').map((para, i) => (
                <p key={i} className="text-sm text-muted-foreground leading-relaxed mb-2">
                  {para}
                </p>
              ))}
            </section>
          ))}
        </div>
      </div>
    </div>
  )
}
